[package]
name = "rust-binary-calls-swift-package"
version = "0.1.0"
edition = "2021"
publish = []

build = "build.rs"

[build-dependencies]
swift-bridge-build = "0.1"

[dependencies]
swift-bridge = "0.1"

[lib]
crate-type=["staticlib", "rlib"]

